import type { MigrationInterface, QueryRunner } from 'typeorm';

export class AddMediaTypeToUniqueConstraints1772048000333 implements MigrationInterface {
  name = 'AddMediaTypeToUniqueConstraints1772048000333';

  private async constraintExists(
    queryRunner: QueryRunner,
    tableName: string,
    constraintName: string
  ): Promise<boolean> {
    const result = await queryRunner.query(
      `SELECT 1 FROM information_schema.table_constraints WHERE table_schema = 'public' AND table_name = $1 AND constraint_name = $2`,
      [tableName, constraintName]
    );

    return result.length > 0;
  }

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Manually added: TypeORM migration:generate does not detect changes to named unique constraints.
    await queryRunner.query(
      `ALTER TABLE "watchlist" DROP CONSTRAINT IF EXISTS "UNIQUE_USER_DB"`
    );
    if (
      !(await this.constraintExists(queryRunner, 'watchlist', 'UNIQUE_USER_DB'))
    ) {
      await queryRunner.query(
        `ALTER TABLE "watchlist" ADD CONSTRAINT "UNIQUE_USER_DB" UNIQUE ("tmdbId", "mediaType", "requestedById")`
      );
    }

    // Auto-generated by TypeORM
    await queryRunner.query(
      `CREATE SEQUENCE IF NOT EXISTS "blocklist_id_seq" OWNED BY "blocklist"."id"`
    );
    await queryRunner.query(
      `ALTER TABLE "blocklist" ALTER COLUMN "id" SET DEFAULT nextval('"blocklist_id_seq"')`
    );
    if (await queryRunner.hasColumn('blocklist', 'externalId')) {
      await queryRunner.query(
        `ALTER TABLE "blocklist" DROP CONSTRAINT IF EXISTS "UQ_6bbafa28411e6046421991ea21c"`
      );
      if (
        !(await this.constraintExists(
          queryRunner,
          'blocklist',
          'UQ_cd389742b9156ca10495f21fe0a'
        ))
      ) {
        await queryRunner.query(
          `ALTER TABLE "blocklist" ADD CONSTRAINT "UQ_cd389742b9156ca10495f21fe0a" UNIQUE ("externalId", "mediaType")`
        );
      }
    } else {
      await queryRunner.query(
        `ALTER TABLE "blocklist" DROP CONSTRAINT IF EXISTS "UQ_6bbafa28411e6046421991ea21c"`
      );
      if (
        !(await this.constraintExists(
          queryRunner,
          'blocklist',
          'UQ_81504e02db89b4c1e3152729fa6'
        ))
      ) {
        await queryRunner.query(
          `ALTER TABLE "blocklist" ADD CONSTRAINT "UQ_81504e02db89b4c1e3152729fa6" UNIQUE ("tmdbId", "mediaType")`
        );
      }
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Manually added: TypeORM migration:generate does not detect changes to named unique constraints.
    await queryRunner.query(
      `ALTER TABLE "watchlist" DROP CONSTRAINT "UNIQUE_USER_DB"`
    );
    await queryRunner.query(
      `ALTER TABLE "watchlist" ADD CONSTRAINT "UNIQUE_USER_DB" UNIQUE ("tmdbId", "requestedById")`
    );

    // Auto-generated by TypeORM
    await queryRunner.query(
      `ALTER TABLE "blocklist" DROP CONSTRAINT "UQ_81504e02db89b4c1e3152729fa6"`
    );
    await queryRunner.query(
      `ALTER TABLE "blocklist" ADD CONSTRAINT "UQ_6bbafa28411e6046421991ea21c" UNIQUE ("tmdbId")`
    );
    await queryRunner.query(
      `ALTER TABLE "blocklist" ALTER COLUMN "id" DROP DEFAULT`
    );
    await queryRunner.query(`DROP SEQUENCE "blocklist_id_seq"`);
  }
}
